# fly.toml app configuration file generated for phoenix-redis on 2023-06-26T12:55:59+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phoenix-redis"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
services = []

[build]
  image = "flyio/redis:6.2"

[env]

[experimental]
  auto_rollback = true
  private_network = true

[metrics]
  path = "/metrics"
  port = 9091

[[mounts]]
  destination = "/data"
  encrypted = false
  source = "redis_server"
